apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: multi-docker
build:
  artifacts:
  - image: mbcatubig14/multi-client-10-14
    context: client
    docker:
      dockerfile: Dockerfile.dev
    sync:
      infer:
      - '**/*.js'
      - '**/*.css'
      - '**/*.html'
deploy:
  kubectl:
    manifests:
    - k8s/client-deployment.yaml
